# Add ACMO Metadata

# --- !Ups

CREATE table acmo_metadata (
			 dataset_id text,
			 created timestamp without time zone DEFAULT now(),
			 suite_id text,
			 exname text,
			 field_overlay text,
			 seasonal_strategy text,
			 rotational_analysis text,
			 runNUM text,
			 trt_name text,
			 clim_id text,
			 clim_rep text,
			 reg_id text,
			 stratum text,
			 rap_id text,
			 man_id text,
			 institution text,
			 rotation text,
			 wst_id text,
			 soil_id text,
			 fl_lat text,
			 fl_long text,
			 crid_text text,
			 cul_id text,
			 cul_name text,
			 sdat text,
			 pdate text,
			 hwah text,
			 cwah text,
			 hdate text,
			 irNUMc text,
			 ir_tot text,
			 irop_text text,
			 fe_NUM text,
			 fen_tot text,
			 fep_tot text,
			 fek_tot text,
			 om_tot text,
			 ti_NUM text,
			 tiimp_text text,
			 eid text,
			 wid text,
			 sid text,
			 doid text,
			 dsid text,
			 drid text,
			 crop_model text,
			 model_ver text,
			 hwah_s text,
			 cwah_s text,
			 adat_s text,
			 mdat_s text,
			 hadat_s text,
			 laix_s text,
			 prcp_s text,
			 etcp_s text,
			 nucm_s text,
			 nlcm_s text
);

# --- !Downs

DROP TABLE acmo_metadata;
